### ISSUE TITLE
Legend set assigned to indicator/dataelement should pull into pivot table dynamically

### ISSUE THREAD

**Issue by ElmarieClaasen** [dhis2/pivot-tables-app#32]
Introduce a new option for pivot table legend set to use legend sets associated with individual data elements, indicators, data sets and program indicators in the pivot table. The option can be called "By data item".

The idea behind this blueprint is to keep it optional, but make it possible to pull in the assigned legend sets per data element. At the moment, the user is only allowed to apply a single legend set to the entire table, no matter which and how many data elements it contains. Present e.g. indicators and data elements with their respective legend sets in the same table.

**Comment by larshelge** [comment]
I don't think we should do this. Legend sets should rather be optional. There might be good reasons for having a legend set for indicators e.g. for GIS without wanting to display them in pivot by default.

**Comment by janhenrikoverland** [comment]
The idea behind this blueprint is to keep it optional, but make it possible to pull in the assigned legend sets per data element. At the moment, the user is only allowed to apply a single legend set to the entire table, no matter which and how many data elements it contains. Would be nice to present different elements with their respective legend sets in the same table.
