### ISSUE TITLE
Show code and description for metadata

### ISSUE THREAD

**Issue by larshelge** [dhis2/pivot-tables-app#37]
For metadata, such as indicators, data elements and category options, display a title (dialog) when hovering over the name. There should be a reasonable delay before the title appears.

The title format should be:

<pre>[code] [description]</pre>

For the data items, the format should be:

<pre>[data-item-type] [code] [description]</pre>

where [data-item-type] is "Indicator", "Data element", "Data set", "Program indicator".

**Comment by janhenrikoverland** [comment]
https://jira.dhis2.org/browse/DHIS2-646
