### ISSUE TITLE
Extended metadata option for data download

### ISSUE THREAD

**Issue by larshelge** [dhis2/pivot-tables-app#42]
Add an option for "extended metadata" for data downloads. When enabled, then all of "name", "uid",  "code", "description" properties should be included. For plain data source, include for all. For table layout download, include for dimensions on rows.

**Comment by janhenrikoverland** [comment]
Moved to Jira.

**Comment by janhenrikoverland** [comment]
https://jira.dhis2.org/browse/DHIS2-645
